"""create blog_products_in_orders

Revision ID: 13ae8c2574d4
Revises: a6fb947267bf
Create Date: 2024-11-17 17:43:46.751215

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "13ae8c2574d4"
down_revision: Union[str, None] = "a6fb947267bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_in_orders",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("products_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["blog_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["blog_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "order_id", name="udx_product_order"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_in_orders")
    # ### end Alembic commands ###
