"""make bio in authors

Revision ID: 33c57dda6f6f
Revises: bd00f19565c3
Create Date: 2024-11-14 17:28:16.057941

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "33c57dda6f6f"
down_revision: Union[str, None] = "bd00f19565c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_authors", sa.Column("bio", sa.Text(), server_default="", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_authors", "bio")
    # ### end Alembic commands ###
