"""add created_at column to users

Revision ID: 39350f4462cd
Revises: 7521f9c293ea
Create Date: 2024-11-14 15:48:06.758821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39350f4462cd"
down_revision: Union[str, None] = "7521f9c293ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "created_at", sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "created_at")
    # ### end Alembic commands ###
