"""Initial Mig

Revision ID: 80bdcc598298
Revises: c03939288a8a
Create Date: 2024-11-23 23:29:09.936241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "80bdcc598298"
down_revision: Union[str, None] = "c03939288a8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "blog_users", sa.Column("email", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "blog_users",
        "username",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.String(length=20),
        existing_nullable=False,
    )
    op.drop_column("blog_users", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blog_users",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "blog_users",
        "username",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=25),
        existing_nullable=False,
    )
    op.drop_column("blog_users", "email")
    op.create_table(
        "blog_orders",
        sa.Column("adress", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "comment",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('blog_orders_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["blog_users.id"], name="blog_orders_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="blog_orders_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "blog_authors",
        sa.Column(
            "name",
            sa.VARCHAR(),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('blog_authors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "bio",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["blog_users.id"], name="blog_authors_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="blog_authors_pkey"),
        sa.UniqueConstraint("user_id", name="blog_authors_user_id_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "blog_posts",
        sa.Column(
            "title",
            sa.VARCHAR(length=200),
            server_default=sa.text("''::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "body",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('blog_posts_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("author_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"], ["blog_authors.id"], name="fk_posts_authors"
        ),
        sa.PrimaryKeyConstraint("id", name="blog_posts_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_blog_posts_title", "blog_posts", ["title"], unique=False)
    op.create_table(
        "blog_products",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "price",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('blog_products_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="blog_products_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "posts_tags_assosiation",
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"], ["blog_posts.id"], name="posts_tags_assosiation_post_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["blog_tags.id"], name="posts_tags_assosiation_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint(
            "post_id", "tag_id", name="posts_tags_assosiation_pkey"
        ),
    )
    op.create_table(
        "blog_tags",
        sa.Column("name", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="blog_tags_pkey"),
        sa.UniqueConstraint("name", name="blog_tags_name_key"),
    )
    op.create_table(
        "product_in_orders",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "products_count",
            sa.INTEGER(),
            server_default=sa.text("1"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("unit_price", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["blog_orders.id"], name="product_in_orders_order_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["blog_products.id"],
            name="product_in_orders_product_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="product_in_orders_pkey"),
        sa.UniqueConstraint("product_id", "order_id", name="udx_product_order"),
    )
    # ### end Alembic commands ###
