"""make posts.title index

Revision ID: bd00f19565c3
Revises: c9570d73ff04
Create Date: 2024-11-14 17:23:44.941228

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bd00f19565c3"
down_revision: Union[str, None] = "c9570d73ff04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_blog_posts_title"), "blog_posts", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_blog_posts_title"), table_name="blog_posts")
    # ### end Alembic commands ###
