"""make column token unique

Revision ID: c03939288a8a
Revises: f36e08a5a56b
Create Date: 2024-11-19 13:36:01.880273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c03939288a8a"
down_revision: Union[str, None] = "f36e08a5a56b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("unique_token_on_user", "blog_users", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_token_on_user", "blog_users", type_="unique")
    # ### end Alembic commands ###
