"""create relationship post to author

Revision ID: c9570d73ff04
Revises: 0aa3686fa3ca
Create Date: 2024-11-14 16:36:51.486668

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c9570d73ff04"
down_revision: Union[str, None] = "0aa3686fa3ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_posts", sa.Column("author_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "fk_posts_authors", "blog_posts", "blog_authors", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_posts_authors", "blog_posts", type_="foreignkey")
    op.drop_column("blog_posts", "author_id")
    # ### end Alembic commands ###
