"""add token column to users table

Revision ID: f36e08a5a56b
Revises: 13ae8c2574d4
Create Date: 2024-11-19 13:16:30.446538

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f36e08a5a56b"
down_revision: Union[str, None] = "13ae8c2574d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("blog_users", sa.Column("token", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("blog_users", "token")
    # ### end Alembic commands ###
