"""Add tables department and employees

Revision ID: f52f2e961f7e
Revises: 974f832e7c0f
Create Date: 2024-11-27 16:44:32.691473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f52f2e961f7e'
down_revision: Union[str, None] = '974f832e7c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_departments',
    sa.Column('name_dep', sa.String(length=255), nullable=False),
    sa.Column('adress_dep', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_employee',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dep_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dep_id'], ['blog_departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_employee')
    op.drop_table('blog_departments')
    # ### end Alembic commands ###
